name: Embedding

on: [push]

jobs:
  embedding:
    runs-on: macOS-latest
    steps:
      - name: Install GNU Prolog backend
        uses: logtalk-actions/setup-gnu-prolog@master
        with:
          gprolog-version: latest
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: git
          logtalk-tool-dependencies: false
      - name: Create an executable from the "spider" text adventure game
        run: |
          mkdir ~/collect
          echo ":- initialization('::'(spider,start))." >> ~/collect/init.pl
          $LOGTALKHOME/scripts/embedding/gprolog/gprolog_embed_logtalk.sh -c -d ~/collect -l $LOGTALKUSER/examples/adventure/spider.lgt -s $LOGTALKUSER/scripts/embedding/settings-embedding-sample.lgt -p $LOGTALKUSER/paths/paths.pl -- --strip --no-top-level ~/collect/init.pl
          mv ~/collect/logtalk ~/collect/spider
      - name: Upload executable
        uses: actions/upload-artifact@master
        with:
          name: spider
          path: /Users/runner/collect/spider
